{
  "openapi": "3.0.1",
  "info": {
    "title": "ë¯¸íŒ…í•™ê°œë¡ ",
    "description": "the matching service for 2030's meeting by NO:ON",
    "contact": {
      "email": "noon.official.dev@gmail.com"
    },
    "version": "1.0.1"
  },
  "externalDocs": {
    "description": "explore github of NO:ON",
    "url": "https://github.com/NOON-official"
  },
  "servers": [
    {
      "url": "http://localhost:5000/api"
    },
    {
      "url": "http://3.39.207.215:5000/api"
    }
  ],
  "tags": [
    {
      "name": "Service",
      "description": "Meetinghakgaeron Service"
    },
    {
      "name": "Auth",
      "description": "auth for user"
    },
    {
      "name": "User",
      "description": "user's team information"
    }
  ],
  "paths": {
    "/service/count/team": {
      "get": {
        "tags": ["Service"],
        "summary": "ëŒ€ê¸°ì¤‘ì¸ íŒ€ ìˆ˜ ì¡°íšŒ",
        "description": "ğŸŒ¸ ë¯¸íŒ…í•™ê°œë¡ ì˜ ëŒ€ê¸°ì¤‘ì¸ íŒ€ ìˆ˜ë¥¼ ì¡°íšŒí•©ë‹ˆë‹¤.",
        "responses": {
          "200": {
            "description": "ëŒ€ê¸°ì¤‘ì¸ íŒ€ ìˆ˜ ì¡°íšŒ ì„±ê³µ",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "message": {
                      "type": "string",
                      "example": "ëŒ€ê¸°ì¤‘ì¸ íŒ€ ìˆ˜ ì¡°íšŒì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "waitingTeam": 12
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/auth/kakao/callback": {
      "get": {
        "tags": ["Auth"],
        "summary": "ì¹´ì¹´ì˜¤ ë¡œê·¸ì¸",
        "description": "ğŸŒ¸ ì¹´ì¹´ì˜¤ ë¡œê·¸ì¸ í›„ Access Token, Refresh Tokenê³¼ í•¨ê»˜ ìœ ì € ì •ë³´ë¥¼ ë°˜í™˜í•©ë‹ˆë‹¤.",
        "responses": {
          "200(1)": {
            "description": "íšŒì›ê°€ì… ì„±ê³µ",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "message": {
                      "type": "string",
                      "example": "íšŒì›ê°€ì…ì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "user": {
                          "accessToken": "adja;kldhj;a.dasjlh;kadjlh;akjh;j.adjlhk;aejh",
                          "birthday": "",
                          "createdAt": "2022-08-15T11:13:16.000Z",
                          "gender": "female",
                          "id": 1,
                          "isDeleted": 0,
                          "kakaoUid": 111281217,
                          "nickname": "ì–„ë£¨",
                          "phone": null,
                          "refreshToken": "adsjg;ldgjk.jdagl;kjad;lgkjad.da;gkljad;lgj",
                          "updatedAt": "2022-08-15T11:13:16.000Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "200(2)": {
            "description": "ë¡œê·¸ì¸ ì„±ê³µ",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "message": {
                      "type": "string",
                      "example": "ë¡œê·¸ì¸ì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "user": {
                          "accessToken": "adja;kldhj;a.dasjlh;kadjlh;akjh;j.adjlhk;aejh",
                          "birthday": "",
                          "createdAt": "2022-08-15T11:13:16.000Z",
                          "gender": "female",
                          "id": 1,
                          "isDeleted": 0,
                          "kakaoUid": 111281217,
                          "nickname": "ì–„ë£¨",
                          "phone": null,
                          "refreshToken": "adsjg;ldgjk.jdagl;kjad;lgkjad.da;gkljad;lgj",
                          "updatedAt": "2022-08-15T11:13:16.000Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "ì¹´ì¹´ì˜¤ ì¸ê°€ì½”ë“œê°€ ì—†ëŠ” ê²½ìš°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 400,
                      "success": false,
                      "message": "ì¸ê°€ì½”ë“œê°€ ì—†ìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "tags": ["Auth"],
        "summary": "í† í° ì¬ë°œê¸‰",
        "description": "ğŸŒ¸ í† í°ì„ ì¬ë°œê¸‰í•©ë‹ˆë‹¤. \n\n ë³µì¡í•´ë³´ì´ì§€ë§Œ ì—ëŸ¬ì½”ë“œê°€ 200, 400, 401ì¸ ê²½ìš°ë¡œ ë¶„ë¥˜í•˜ì—¬ 401ì¸ ê²½ìš° ëª¨ë‘ ìƒˆë¡œ ë¡œê·¸ì¸í•˜ë„ë¡ ì²˜ë¦¬í•´ì£¼ë©´ ë©ë‹ˆë‹¤! (ë¡œê·¸ì¸ í˜ì´ì§€ë¡œ ì´ë™ì‹œí‚¤ê¸°)",
        "parameters": [
          {
            "in": "header",
            "name": "authorization",
            "schema": {
              "type": "string",
              "format": "Bearer {token}",
              "example": "Bearer addagkjdagjdakg.djagkjdgkadjgk.ajdkglajdlgkj"
            },
            "required": true,
            "description": "Access Token"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "grant_type": {
                    "type": "string",
                    "example": "refresh_token",
                    "description": "ê³ ì •ê°’"
                  },
                  "refresh_token": {
                    "type": "string",
                    "format": "text",
                    "example": "addagkjdagjdakg.djagkjdgkadjgk.ajdkglajdlgkj"
                  },
                  "userId": {
                    "type": "integer",
                    "example": 1
                  }
                },
                "required": ["grant_type", "refresh_token", "userId"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "í† í° ì¬ë°œê¸‰ ì„±ê³µ",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "message": {
                      "type": "string",
                      "example": "í† í° ì¬ë°œê¸‰ì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "user": {
                          "accessToken": "adja;kldhj;a.dasjlh;kadjlh;akjh;j.adjlhk;aejh",
                          "birthday": "",
                          "createdAt": "2022-08-15T11:13:16.000Z",
                          "gender": "female",
                          "id": 1,
                          "isDeleted": 0,
                          "kakaoUid": 111281217,
                          "nickname": "ì–„ë£¨",
                          "phone": null,
                          "refreshToken": "adsjg;ldgjk.jdagl;kjad;lgkjad.da;gkljad;lgj",
                          "updatedAt": "2022-08-15T11:13:16.000Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "ìœ íš¨í•œ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 400,
                      "success": false,
                      "message": "ë§Œë£Œë˜ì§€ ì•Šì€ í† í°ì…ë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(1)": {
            "description": "í† í° ì—†ìŒ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ì—†ìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(2)": {
            "description": "í—ˆê°€ ìœ í˜• ì—†ìŒ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "ì˜¬ë°”ë¥´ì§€ ì•Šì€ í—ˆê°€ ìœ í˜•ì…ë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(3)": {
            "description": "ìœ ì € ì•„ì´ë”” ì—†ìŒ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "ìœ ì € ì•„ì´ë””ê°€ ì—†ìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(4)": {
            "description": "ìœ íš¨í•˜ì§€ ì•Šì€ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(5)": {
            "description": "ë§Œë£Œëœ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ë§Œë£Œë˜ì—ˆìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/user/ourteam": {
      "post": {
        "tags": ["User"],
        "summary": "ìœ ì € ì •ë³´ ì €ì¥",
        "description": "ğŸŒ¸ ë§¤ì¹­ì„ ì‹ ì²­í•˜ëŠ” ìœ ì €ì˜ íŒ€ ì •ë³´ë¥¼ ì €ì¥í•©ë‹ˆë‹¤. \n\nì¹´ì¹´ì˜¤ ë¡œê·¸ì¸ì— ì„±ê³µí•œ í›„ ë°œê¸‰ë˜ëŠ” í† í°ê³¼ í•¨ê»˜ ë³¸ APIë¥¼ í˜¸ì¶œí•´ì£¼ì‹œë©´ ë©ë‹ˆë‹¤! \n\nì—ëŸ¬1. í† í°ì´ ë§Œë£Œëœ ê²½ìš° api/auth/refresh í˜¸ì¶œí•˜ì—¬ í† í° ì¬ë°œê¸‰ í›„ ë‹¤ì‹œ í˜¸ì¶œ \n\nì—ëŸ¬2. í† í°ì´ ìœ íš¨í•˜ì§€ ì•Šì€ ê²½ìš° ì¬ë¡œê·¸ì¸ í•´ì£¼ì‹œë©´ ë©ë‹ˆë‹¤!",
        "parameters": [
          {
            "in": "header",
            "name": "authorization",
            "schema": {
              "type": "string",
              "format": "Bearer {token}",
              "example": "Bearer addagkjdagjdakg.djagkjdgkadjgk.ajdkglajdlgkj"
            },
            "required": true,
            "description": "Access Token"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "userId": {
                    "type": "integer",
                    "example": "1"
                  },
                  "gender": {
                    "type": "string",
                    "format": "varchar(2)",
                    "example": "ë‚¨ì„±"
                  },
                  "num": {
                    "type": "string",
                    "format": "varchar(3)",
                    "example": "3:3"
                  },
                  "age": {
                    "type": "string",
                    "format": "varchar(2)",
                    "example": "25"
                  },
                  "intro": {
                    "type": "string",
                    "format": "text",
                    "example": "ì•ˆë…•í•˜ì„¸ìš”. ì €í¬ëŠ”~"
                  },
                  "job": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 4,
                    "example": ["ëŒ€í•™ìƒ", "ì·¨ì¤€ìƒ"]
                  },
                  "university": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 3,
                    "example": ["ê²½í¬ëŒ€í•™êµ", "ì„œìš¸ì‹œë¦½ëŒ€í•™êµ", "ë‹¤ë¥¸ í•™êµì—ìš”"]
                  },
                  "area": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 4,
                    "example": ["í™ëŒ€/í•©ì •", "ê°•ë‚¨", "ê±´ëŒ€"]
                  },
                  "day": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 7,
                    "example": ["ì›”ìš”ì¼", "í† ìš”ì¼", "ì¼ìš”ì¼"]
                  },
                  "appearance": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 5,
                    "example": ["ê³ ì–‘ì´ìƒ", "ê°•ì•„ì§€ìƒ"]
                  },
                  "mbti": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 16,
                    "example": ["ISFP", "ENTP"]
                  },
                  "fashion": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 10,
                    "example": ["ìºì£¼ì–¼", "ë¹„ì¦ˆë‹ˆìŠ¤", "ë² ì´ì§", "ì•„ë©”ì¹´ì§€"]
                  },
                  "role": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 4,
                    "example": ["ê¹ë‘ê¸°", "ì‚¬íšŒì", "ë¹„ì£¼ì–¼"]
                  }
                },
                "required": [
                  "userId",
                  "gender",
                  "num",
                  "age",
                  "intro",
                  "job",
                  "university",
                  "area",
                  "day",
                  "appearance",
                  "mbti",
                  "fashion",
                  "role"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "ìœ ì € ì •ë³´ ì €ì¥ ì„±ê³µ",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "message": {
                      "type": "string",
                      "example": "ìœ ì € ì •ë³´ ì €ì¥ì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "ourteamId": 2
                      }
                    }
                  }
                }
              }
            }
          },
          "400(1)": {
            "description": "ìœ íš¨í•˜ì§€ ì•Šì€ ê°’",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 400,
                      "success": false,
                      "message": "í•„ìˆ˜ í•­ëª©ì„ ëª¨ë‘ ì…ë ¥í•´ì£¼ì„¸ìš”"
                    }
                  }
                }
              }
            }
          },
          "400(2)": {
            "description": "í† í° ì—†ìŒ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 400,
                      "success": false,
                      "message": "í† í°ì´ ì—†ìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(1)": {
            "description": "ìœ íš¨í•˜ì§€ ì•Šì€ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(2)": {
            "description": "ë§Œë£Œëœ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ë§Œë£Œë˜ì—ˆìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "ì¡´ì¬í•˜ì§€ ì•ŠëŠ” ìœ ì €",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 404,
                      "success": false,
                      "message": "ì¡´ì¬í•˜ì§€ ì•ŠëŠ” ìœ ì €ì…ë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/user/preference": {
      "post": {
        "tags": ["User"],
        "summary": "ìœ ì € ì„ í˜¸ ì •ë³´ ì €ì¥",
        "description": "ğŸŒ¸ ë§¤ì¹­ì„ ì‹ ì²­í•˜ëŠ” ìœ ì €ì˜ ì„ í˜¸ ì •ë³´ë¥¼ ì €ì¥í•©ë‹ˆë‹¤. \n\n âœ¨ì¤‘ìš”: ìœ ì € ì •ë³´ ì €ì¥ API(api/user/ourteam)ë¥¼ ë¨¼ì € í˜¸ì¶œí•˜ì‹  ë‹¤ìŒ, **ì„±ê³µ responseë¥¼ ë°›ì€ í›„(status:200)** ë³¸ APIë¥¼ í˜¸ì¶œí•´ì£¼ì„¸ìš”! \n *  ìœ ì € ì •ë³´ ì €ì¥ API(api/user/ourteam)ì˜ responseì— ë‹´ê²¨ìˆëŠ” ourteamId ê°’ì„ ë³¸ API í˜¸ì¶œ ì‹œ í•¨ê»˜ ë³´ë‚´ì£¼ì‹œë©´ ë©ë‹ˆë‹¤. \n * ì„±ê³µ responseì˜ dataëŠ” í˜„ì¬ ì“°ì´ëŠ” ê³³ì´ ì—†ì–´ì„œ ì„ì‹œë¡œ success=trueë¥¼ ë°˜í™˜í•©ë‹ˆë‹¤!",
        "parameters": [
          {
            "in": "header",
            "name": "authorization",
            "schema": {
              "type": "string",
              "format": "Bearer {token}",
              "example": "Bearer addagkjdagjdakg.djagkjdgkadjgk.ajdkglajdlgkj"
            },
            "required": true,
            "description": "Access Token"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "ourteamId": {
                    "type": "integer",
                    "example": 2
                  },
                  "job": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 4,
                    "example": ["ëŒ€í•™ìƒ", "ì·¨ì¤€ìƒ"]
                  },
                  "age": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 2,
                    "maxitems": 2,
                    "example": ["21", "25"]
                  },
                  "sameUniversity": {
                    "type": "integer",
                    "example": 1,
                    "description": "0: ê°™ì€ í•™êµëŠ” ì‹«ì–´ìš”, 1: ìƒê´€ ì—†ì–´ìš”"
                  },
                  "vibe": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "minitems": 1,
                    "maxitems": 7,
                    "example": ["ëŒ€í™”ê°€ ì¢‹ì•„ìš”", "ì¬ë¯¸"]
                  }
                },
                "required": ["ourteamId", "job", "age", "same", "sameUniversity", "vibe"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "ìœ ì € ì„ í˜¸ ì •ë³´ ì €ì¥ ì„±ê³µ",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "message": {
                      "type": "string",
                      "example": "ìœ ì € ì„ í˜¸ ì •ë³´ ì €ì¥ì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "success": true
                      }
                    }
                  }
                }
              }
            }
          },
          "400(1)": {
            "description": "ìœ íš¨í•˜ì§€ ì•Šì€ ê°’",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 400,
                      "success": false,
                      "message": "í•„ìˆ˜ í•­ëª©ì„ ëª¨ë‘ ì…ë ¥í•´ì£¼ì„¸ìš”"
                    }
                  }
                }
              }
            }
          },
          "400(2)": {
            "description": "í† í° ì—†ìŒ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 400,
                      "success": false,
                      "message": "í† í°ì´ ì—†ìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(1)": {
            "description": "ìœ íš¨í•˜ì§€ ì•Šì€ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(2)": {
            "description": "ë§Œë£Œëœ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ë§Œë£Œë˜ì—ˆìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "ì¡´ì¬í•˜ì§€ ì•ŠëŠ” ìœ ì €",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 404,
                      "success": false,
                      "message": "ì¡´ì¬í•˜ì§€ ì•ŠëŠ” ìœ ì €ì…ë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/user/phone": {
      "post": {
        "tags": ["User"],
        "summary": "ìœ ì € í•¸ë“œí° ë²ˆí˜¸ ì €ì¥",
        "description": "ğŸŒ¸ ë§¤ì¹­ì„ ì‹ ì²­í•˜ëŠ” ìœ ì €ì˜ í•¸ë“œí° ë²ˆí˜¸ë¥¼ ì €ì¥í•©ë‹ˆë‹¤.",
        "parameters": [
          {
            "in": "header",
            "name": "authorization",
            "schema": {
              "type": "string",
              "format": "Bearer {token}",
              "example": "Bearer addagkjdagjdakg.djagkjdgkadjgk.ajdkglajdlgkj"
            },
            "required": true,
            "description": "Access Token"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "userId": {
                    "type": "integer",
                    "example": 1
                  },
                  "phone": {
                    "type": "string",
                    "format": "varchar(13)"
                  }
                },
                "required": ["ourteamId", "phone"]
              },
              "examples": {
                "1": {
                  "value": { "userId": 1, "phone": "01012345678" }
                },
                "2": {
                  "value": { "userId": 1, "phone": "010-1234-5678" }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "ìœ ì € í•¸ë“œí° ë²ˆí˜¸ ì €ì¥ ì„±ê³µ",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "success": {
                      "type": "boolean",
                      "example": true
                    },
                    "message": {
                      "type": "string",
                      "example": "ìœ ì € í•¸ë“œí° ë²ˆí˜¸ ì €ì¥ì— ì„±ê³µí•˜ì˜€ìŠµë‹ˆë‹¤"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "success": true
                      }
                    }
                  }
                }
              }
            }
          },
          "400(1)": {
            "description": "ìœ íš¨í•˜ì§€ ì•Šì€ ê°’",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 400,
                      "success": false,
                      "message": "í•„ìˆ˜ í•­ëª©ì„ ëª¨ë‘ ì…ë ¥í•´ì£¼ì„¸ìš”"
                    }
                  }
                }
              }
            }
          },
          "400(2)": {
            "description": "í† í° ì—†ìŒ",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 400,
                      "success": false,
                      "message": "í† í°ì´ ì—†ìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(1)": {
            "description": "ìœ íš¨í•˜ì§€ ì•Šì€ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "401(2)": {
            "description": "ë§Œë£Œëœ í† í°",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 401,
                      "success": false,
                      "message": "í† í°ì´ ë§Œë£Œë˜ì—ˆìŠµë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "ì¡´ì¬í•˜ì§€ ì•ŠëŠ” ìœ ì €",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Fail"
                },
                "examples": {
                  "1": {
                    "summary": "Response Body",
                    "value": {
                      "status": 404,
                      "success": false,
                      "message": "ì¡´ì¬í•˜ì§€ ì•ŠëŠ” ìœ ì €ì…ë‹ˆë‹¤"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Service": {
        "type": "object",
        "properties": {
          "waitingTeam": {
            "type": "integer",
            "example": 12
          }
        }
      },
      "Success": {
        "type": "object",
        "required": ["status", "success", "message", "data"],
        "properties": {
          "status": {
            "type": "integer"
          },
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        }
      },
      "Fail": {
        "type": "object",
        "required": ["status", "success", "message"],
        "properties": {
          "status": {
            "type": "integer"
          },
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        }
      }
    },
    "responses": {
      "NullValue": {
        "description": "Request Bodyì— í•„ìš”í•œ ê°’ì´ ì—†ìŒ",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Fail"
            },
            "examples": {
              "1": {
                "summary": "Response Body",
                "value": {
                  "status": 400,
                  "success": false,
                  "message": "í•„ìš”í•œ ê°’ì´ ì—†ìŠµë‹ˆë‹¤"
                }
              }
            }
          }
        }
      },
      "InternalServerError": {
        "description": "ì„œë²„ ë‚´ë¶€ ì˜¤ë¥˜",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Fail"
            },
            "examples": {
              "1": {
                "summary": "Response Body",
                "value": {
                  "status": 500,
                  "success": false,
                  "message": "ì„œë²„ ë‚´ ì˜¤ë¥˜"
                }
              }
            }
          }
        }
      }
    }
  }
}
